TOOL_PATH = 'tools/'
RES_PATH = 'res/'
PHOBERT_VER = 'vinai/phobert-base-v2'
MAX_LEN = 200
PHOBERT_BATCH_SIZE = 512

EMOJI_NEG = '<EMOJI_NEGATIVE>'
EMOJI_NEU = '<EMOJI_NEUTRAL>'
EMOJI_POS = '<EMOJI_POSITIVE>'
